variables:
- name: BuildParameters.solution
  value: '**\*.sln'
- name: BuildParameters.ArtifactName
  value: drop
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Default
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: NuGetToolInstaller@0
    displayName: Use NuGet 6.0
    inputs:
      versionSpec: 6.0
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: $(BuildParameters.solution)
  - task: VSBuild@1
    displayName: Build solution
    inputs:
      solution: $(BuildParameters.solution)
      msbuildArgs: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
  - task: NuGetCommand@2
    displayName: NuGet pack
    inputs:
      command: pack
      versioningScheme: byPrereleaseNumber
  - task: NuGetCommand@2
    displayName: NuGet push
    inputs:
      command: push
      feedPublish: 7e467d4b-2a46-4ac1-a366-ac8a635bdb11/2d6c6f6a-5a87-44b2-93cc-ea608ee91160
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: $(BuildParameters.ArtifactName)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
